### ISSUE TITLE
It does not work. Symlinks in node_modules are deleted anyway

### ISSUE THREAD

**Issue by ibc** [UD-UD/npm-safe-install#1]
I've a manually created soft link in my app:

```bash
/home/ibc/src/myproject/ $ ls -l node_modules

// Soft link
somedep => /home/ibc/src/somedep
```

Then I install another dep using `nsi`:

```bash
/home/ibc/src/myproject/ $ nsi express
```

It removes the above `somedep` soft link and makes a fresh install from NPM registry. And worse, `nsi` does not print the installation output of `somedep` (which produces lot of verbose output during its installation).

So, not sure how `nsi` is usesful at all. Perhaps I understood its purpose wrong?

**Comment by ibc** [comment]
> And worse, nsi does not print the installation output of somedep (which produces lot of verbose output during its installation).

NOTE: It does, but at the end once the `nsi` command terminates. Not very cool. Installation logs should be shown in real-time.

**Comment by UD-UD** [comment]
Thanks for your feedback @ibc 

nsi re-links your modules which you have linked by running `npm link` in your dependent project.

If you had project A and B, after running `npm link` in B , when you run `npm link B ` in A,it creates a symlink.Now nsi can preserve those symlinks.

Please visit this [**blog**](https://medium.com/@UD_UD/finally-npm-install-and-npm-link-walks-hand-in-hand-79f7fb6fc258) which will give some idea about the working principle behind nsi. 

I will consider your usecase and make it available in next release. As far as the logs are concerned, that is already in pipeline for next release.

**Comment by ibc** [comment]
Thanks, very useful information.
