### ISSUE TITLE
Even using npm link, linked deps are locally reinstalled when running nsi

### ISSUE THREAD

**Issue by ibc** [UD-UD/npm-safe-install#2]
Scenario:

* I have the source code of a Node module called [mediasoup](https://github.com/versatica/mediasoup/) in my `src/mediasoup` folder.

* I enter there and run `npm link` so I get a symlink as follows:

```
/usr/local/lib/node_modules/mediasoup -> /Users/ibc/src/mediasoup
```

* Then I have another project that uses mediasoup as dependency (so it includes `mediasoup` in its package.json). This is in `src/myapp`.

* I enter there and run `npm link mediasoup` so I get a symlink as follows:

```
/Users/ibc/src/myapp/node_modules/mediasoup -> /usr/local/lib/node_modules/mediasoup -> /Users/ibc/src/mediasoup
```

* Great.

* Then, still in `src/myapp` I run `nsi` or `nsi express` or whatever.

* Somehow the link in `node_modues/mediasoup` is removed and the `mediasoup` dep is installed as normal (which takes lot of time because it must compile lot of C/C++ code).

AFAIU this is not the expected behavior. Am I wrong?

**Comment by UD-UD** [comment]
I couldn't reproduce the issue. 
I think when you link your submodule using `npm link ` you don't need to specify it again in package.json. Remove the dependency from package.json and do a fresh install after removing the node_modules. If you don't want to again run `npm link mediasoup` just create a .nsi.json file in root directory and provide the package name as said in the README. I guess this will solve your problem..Let me know if this work.

Also please run `ls -l ` in node_modules of your main project and show me what symlink is being used

Thanks.

**Comment by ibc** [comment]
So I need to remove my `mediasoup` dep from `package.json`. Otherwise, despite I use `npm install xxxx` or `nsi xxxx`, both ways will end doing a fresh install of `mediasoup`.

I understand the rationale. However that's not valid for me. I just cannot modify the `package.json` that way because eventually I'll need to push my code or because I'll need to update my Docker image, etc, and that cannot happen with a wrong `package.json` that does not include the `mediasoup` dep.

I think the main problem here is npm. Thanks a lot for your support.
